
cc_library(
    name = "mock_hw",
    srcs = [
        "src/MockHw.cpp",
        "src/MockHwImpl.cpp",
        "src/MockHwImpl.hpp",
    ],
    hdrs = [
        "public/MockHw.hpp",
    ],
    strip_include_prefix = "public",
    visibility = ["//visibility:public"],
)
